server:
  port: 7090
spring:
  application:
    name: CLOUD-GATEWAY
  cloud:
    gateway:
      routes:
      - id: ORDER-SERVICE
        uri: lb://ORDER-SERVICE
        predicates:
        - Path=/api/v1/orders/**
      - id: PAYMENT-SERVICE
        uri: lb://PAYMENT-SERVICE
        predicates:
        - Path=/api/v1/payment/**