server:
  port: 7091
  
spring:
  application:
    name: CONFIG-SERVER
    
  cloud:
    config:
      server:
        git:
          clone-on-start: true
          uri: https://github.com/Soumya1910/SpringBoot-Microservice
  profiles:
    active: native